### ISSUE TITLE
Compile errors TensorFlow_Lite_Class.cpp

### ISSUE THREAD

**Issue by barthm1** [Qengineering/TensorFlow_Lite_Classification_RPi_64-bits#1]
switch (interpreter->tensor(output)->type) {
        case kTfLiteFloat32:
            tflite::label_image::get_top_n<float>(interpreter->typed_output_tensor<float>(0), output_size,
                                                    5, threshold, &top_results, true);
        break;
        case kTfLiteUInt8:
            tflite::label_image::get_top_n<uint8_t>(interpreter->typed_output_tensor<uint8_t>(0), output_size,
                                                    5, threshold, &top_results, false);
        break;

/root/TensorFlow_Lite_RPi_64-bits/TensorFlow_Lite_Class.cpp|118|error: cannot convert â€˜boolâ€™ to â€˜TfLiteTypeâ€™|
/root/tensorflow/tensorflow/lite/examples/label_image/get_top_n_impl.h|35|note:   initializing argument 6 of â€˜void tflite::label_image::get_top_n(T*, int, size_t, float, std::vector<std::pair<float, int> >*, TfLiteType) [with T = float; size_t = long unsigned int]â€™|

Using Ubuntu 20.04 or RaspiOS 64

**Comment by Qengineering** [comment]
Your error was caused by type casting a TfLiteType to a boolean. It seems TF Lite doesn't support this casting any more. I've fixed it in the code. Please reload the TensorFlow_Lite_Class.cpp and recompile.
